version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: test-postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  echo-server:
    build:
      context: ./tools/echo-server
      dockerfile: Dockerfile-fixed
    container_name: echo-server
    ports:
      - "8080:8080"
